import { describe, expect, it } from 'vitest'
import source from './CompactionProcessPanel.vue?raw'

describe('CompactionProcessPanel table', () => {
  it('orders file count and size columns by input then output', () => {
    const inputCount = source.indexOf("setSort('input-files')")
    const inputSize = source.indexOf("setSort('input-size')")
    const outputCount = source.indexOf("setSort('output-files')")
    const outputSize = source.indexOf("setSort('output-size')")

    expect(inputCount).toBeGreaterThan(-1)
    expect(inputSize).toBeGreaterThan(inputCount)
    expect(outputCount).toBeGreaterThan(inputSize)
    expect(outputSize).toBeGreaterThan(outputCount)
  })

  it('sorts detail file lists by time range ascending by default', () => {
    expect(source).toContain("const inputFileSortKey = ref<CompactionProcessFileSortKey>('time-range')")
    expect(source).toContain("const inputFileSortDirection = ref<SortDirection>('asc')")
    expect(source).toContain("const outputFileSortKey = ref<CompactionProcessFileSortKey>('time-range')")
    expect(source).toContain("const outputFileSortDirection = ref<SortDirection>('asc')")
  })

  it('offers a visualization tab for compaction input/output relationships', () => {
    expect(source).toContain("const activeTab = ref<ProcessTab>('table')")
    expect(source).toContain("@click=\"activeTab = 'visualization'\"")
    expect(source).toContain('Compaction graph')
    expect(source).toContain('<svg')
  })

  it('renders file nodes as size-scaled circles', () => {
    expect(source).toContain('function fileNodeRadius')
    expect(source).toContain(':r="fileNodeRadius(node.file.sizeBytes)"')
    expect(source).toContain('function graphFileNodeClass')
    expect(source).toContain("role: GraphFileNode['role']")
  })

  it('links an output file to a later task when it becomes an input', () => {
    expect(source).toContain('const lineageLinks = computed')
    expect(source).toContain('latestOutputByFileId')
    expect(source).toContain('function lineagePath')
    expect(source).toContain('graph-lineage-link')
    expect(source).toContain('Continued input')
  })

  it('lays all tasks into one correlated left-to-right flow', () => {
    expect(source).toContain('const graphLayout = computed')
    expect(source).toContain('fileNodeById')
    expect(source).toContain('taskNodes')
    expect(source).toContain('graphLinks')
    expect(source).toContain('function graphLinkPath')
    expect(source).toContain('v-for="link in graphLayout.graphLinks"')
    expect(source).toContain('v-for="node in graphLayout.fileNodes"')
  })

  it('clips graph links to node boundaries instead of node centers', () => {
    expect(source).toContain('fromRadius:')
    expect(source).toContain('toRadius:')
    expect(source).toContain('function clipLinkEndpoint')
    expect(source).toContain('const start = clipLinkEndpoint')
    expect(source).toContain('const end = clipLinkEndpoint')
  })

  it('aims graph arrows along the center-to-center line', () => {
    expect(source).toContain('return `M ${start.x} ${start.y} L ${end.x} ${end.y}`')
  })

  it('declares zoom and pan contracts for the graph canvas', () => {
    expect(source).toContain('const graphScale = ref(1)')
    expect(source).toContain('const graphPan = ref({ x: 0, y: 0 })')
    expect(source).toContain('function handleGraphWheel')
    expect(source).toContain('@wheel.prevent="handleGraphWheel"')
    expect(source).toContain('function handleGraphPointerDown')
    expect(source).toContain('function handleGraphPointerMove')
    expect(source).toContain('function handleGraphPointerUp')
    expect(source).toContain(':transform="graphTransform"')
  })

  it('converts pointer movement through the SVG viewBox for graph interactions', () => {
    expect(source).toContain('function graphClientPoint')
    expect(source).toContain('getBoundingClientRect()')
    expect(source).toContain('graphLayout.value.width / rect.width')
    expect(source).toContain('graphLayout.value.height / rect.height')
    expect(source).toContain('const graphPointBeforeZoom')
    expect(source).toContain('@lostpointercapture="handleGraphPointerCancel"')
    expect(source).toContain('releasePointerCapture(event.pointerId)')
  })

  it('simplifies graph node labels while keeping hover context', () => {
    expect(source).toContain('function graphFileShortLabel')
    expect(source).toContain('return `${file.fileId} · L${file.level} · ${formatBytes(file.sizeBytes)}`')
    expect(source).toContain("return `${file.fileId.slice(0, 8)}...${file.fileId.slice(-4)}`")
    expect(source).toContain('{{ graphFileShortLabel(node.file) }}')
    expect(source).not.toContain('{{ graphFileLabel(node.file) }}</text>')
    expect(source).toContain('{{ formatMaybeDuration(node.task.mergeMillis) }}')
    expect(source).toContain('textLength="38"')
    expect(source).toContain('font-size: 9px;')
  })

  it('selects graph nodes and shows a floating details popover', () => {
    expect(source).toContain('type SelectedGraphNode')
    expect(source).toContain('const selectedGraphNode = ref<SelectedGraphNode | null>(null)')
    expect(source).toContain('const pendingGraphSelection = ref<SelectedGraphNode | null>(null)')
    expect(source).toContain('const graphDidDrag = ref(false)')
    expect(source).toContain('const graphDragThreshold = 4')
    expect(source).toContain('const graphSvgRef = ref<SVGSVGElement | null>(null)')
    expect(source).toContain('const graphCanvasRef = ref<HTMLElement | null>(null)')
    expect(source).toContain('graphViewportRevision.value\n      if (!selectedGraphNode.value) return {}')
    expect(source).toContain('function graphCssPoint')
    expect(source).toContain('const graphRenderedScale')
    expect(source).toContain('x: canvas.scrollLeft + svgRect.left - canvasRect.left')
    expect(source).toContain('y: canvas.scrollTop + svgRect.top - canvasRect.top')
    expect(source).toContain('function selectGraphFile')
    expect(source).toContain('function selectGraphTask')
    expect(source).toContain('function prepareGraphFileSelection')
    expect(source).toContain('function prepareGraphTaskSelection')
    expect(source).toContain('@pointerdown="prepareGraphFileSelection(node)"')
    expect(source).toContain('@pointerdown="prepareGraphTaskSelection(node)"')
    expect(source).toContain('if (!graphDidDrag.value && pendingGraphSelection.value)')
    expect(source).toContain('function handleGraphPointerCancel')
    expect(source).toContain('@pointercancel="handleGraphPointerCancel"')
    expect(source).toContain('@lostpointercapture="handleGraphPointerCancel"')
    expect(source).toContain('pendingGraphSelection.value = null')
    expect(source).not.toContain('@click="clearGraphSelection"')
    expect(source).toContain('@click.stop')
    expect(source).not.toContain('@pointerdown.stop')
    expect(source).toContain('role="button"')
    expect(source).toContain('tabindex="0"')
    expect(source).toContain('@keydown.enter.stop.prevent')
    expect(source).toContain('@keydown.space.stop.prevent')
    expect(source).toContain('class="graph-popover"')
    expect(source).toContain('selectedGraphNode.kind === \'file\'')
    expect(source).toContain('selectedGraphNode.kind === \'task\'')
    expect(source).toContain('Time range')
    expect(source).toContain('Fan-out')
  })

  it('shows a passive miniature overview only while graph is zoomed in', () => {
    expect(source).toContain('const showGraphMinimap = computed(() => graphScale.value > 1.05)')
    expect(source).toContain('const graphViewportRevision = ref(0)')
    expect(source).toContain('function refreshGraphViewport')
    expect(source).toContain('graphViewportRevision.value')
    expect(source).toContain('@scroll="refreshGraphViewport"')
    expect(source).toContain("addEventListener('resize', refreshGraphViewport)")
    expect(source).toContain('class="graph-minimap"')
    expect(source).toContain('.graph-wrap {\n  position: relative;')
    expect(source).toContain('v-if="showGraphMinimap"')
    expect(source).toContain('class="graph-minimap-viewport"')
    expect(source).toContain('graphMinimapViewport')
  })

  it('limits the graph panel height to the viewport and scrolls the graph canvas', () => {
    expect(source).toContain('max-height: calc(100vh - 120px);')
    expect(source).toContain('display: flex;')
    expect(source).toContain('flex-direction: column;')
    expect(source).toContain('flex: 1;')
    expect(source).toContain('min-height: 0;')
  })

  it('uses compact spacing for graph rows and columns', () => {
    expect(source).toContain('const rowGap = 56')
    expect(source).toContain('const fileColumnGap = 230')
    expect(source).toContain('const taskColumnGap = 230')
    expect(source).toContain('Math.max(900, ...fileNodes.map')
  })

  it('supports tracing ancestors and descendants for the selected graph node', () => {
    expect(source).toContain('const tracedGraphNode = ref<SelectedGraphNode | null>(null)')
    expect(source).toContain('const traceGraphTasks = computed(() =>')
    expect(source).toContain('const ancestorFileIds = new Set(seedFileIds)')
    expect(source).toContain('const descendantFileIds = new Set(seedFileIds)')
    expect(source).toContain('const tracedFileIds = new Set(seedFileIds)')
    expect(source).toContain('function traceGraphNode')
    expect(source).toContain('function clearGraphTrace')
    expect(source).toContain('function addAncestorTasks')
    expect(source).toContain('function addDescendantTasks')
    expect(source).toContain('task.inputFiles.some(file => fileIds.has(file.fileId))')
    expect(source).toContain('task.outputFiles.some(file => fileIds.has(file.fileId))')
    expect(source).not.toContain('task.inputFiles.forEach(file => fileIds.add(file.fileId))')
    expect(source).toContain('const graphLayoutTasks = computed(() => tracedGraphNode.value ? traceGraphTasks.value : graphTasks.value)')
    expect(source).toContain('graphLayoutTasks.value.forEach')
    expect(source).toContain('@click.stop="traceGraphNode"')
    expect(source).toContain('Trace')
    expect(source).toContain('@click="clearGraphTrace"')
    expect(source).toContain('Clear Trace')
  })

  it('styles graph interaction affordances for panning and readable overlays', () => {
    expect(source).toContain('const isGraphDragging = computed(() => graphDrag.value !== null)')
    expect(source).toContain(':class="[\'graph-canvas\', { dragging: isGraphDragging }]"')
    expect(source).toContain('.graph-canvas svg {')
    expect(source).toContain('cursor: grab;')
    expect(source).toContain('.graph-canvas.dragging svg {')
    expect(source).toContain('cursor: grabbing;')
    expect(source).toContain('.graph-file-node {')
    expect(source).toContain('.graph-task-node {')
    expect(source).toContain('.graph-popover {')
    expect(source).toContain('background: rgba(15, 23, 42, 0.96);')
    expect(source).toContain('.graph-minimap-viewport {')
    expect(source).toContain('.graph-file-label {')
    expect(source).toContain('font-size: 10px;')
  })
})
