import { describe, expect, it } from 'vitest'
import source from './CompactionProcessPanel.vue?raw'

describe('CompactionProcessPanel table', () => {
  it('orders file count and size columns by input then output', () => {
    const inputCount = source.indexOf("setSort('input-files')")
    const inputSize = source.indexOf("setSort('input-size')")
    const outputCount = source.indexOf("setSort('output-files')")
    const outputSize = source.indexOf("setSort('output-size')")

    expect(inputCount).toBeGreaterThan(-1)
    expect(inputSize).toBeGreaterThan(inputCount)
    expect(outputCount).toBeGreaterThan(inputSize)
    expect(outputSize).toBeGreaterThan(outputCount)
  })

  it('sorts detail file lists by time range ascending by default', () => {
    expect(source).toContain("const inputFileSortKey = ref<CompactionProcessFileSortKey>('time-range')")
    expect(source).toContain("const inputFileSortDirection = ref<SortDirection>('asc')")
    expect(source).toContain("const outputFileSortKey = ref<CompactionProcessFileSortKey>('time-range')")
    expect(source).toContain("const outputFileSortDirection = ref<SortDirection>('asc')")
  })

  it('precomputes merge severity for table rows instead of sorting per row', () => {
    expect(source).toContain('getMergeTimeSeverityMap')
    expect(source).toContain('const mergeTimeSeverities = computed(() => getMergeTimeSeverityMap(props.analysis.tasks))')
    expect(source).toContain('mergeTimeSeverities.value.get(task)')
    expect(source).not.toContain('getMergeTimeSeverity(task, props.analysis.tasks)')
  })

  it('filters table tasks by searched file lineage', () => {
    expect(source).toContain("const processFileSearch = ref('')")
    expect(source).toContain('const searchedTaskKeys = computed(() =>')
    expect(source).toContain('file.fileId.toLowerCase().includes(query)')
    expect(source).toContain('addAncestorTasks(ancestorFileIds, taskIds, tracedFileIds)')
    expect(source).toContain('addDescendantTasks(descendantFileIds, taskIds, tracedFileIds)')
    expect(source).toContain('const tableTasks = computed(() =>')
    expect(source).toContain('sortedTasks.value.filter(task => searchedTaskKeys.value.has(taskKey(task)))')
    expect(source).toContain('v-model="processFileSearch"')
    expect(source).toContain('Search input file lineage')
    expect(source).toContain('v-for="task in tableTasks"')
  })

  it('expands and highlights directly matched file tasks by default', () => {
    expect(source).toContain('const directlyMatchedTaskKeys = computed(() =>')
    expect(source).toContain('const defaultExpandedTaskKey = computed(() =>')
    expect(source).toContain('expandedTaskKey.value ?? defaultExpandedTaskKey.value')
    expect(source).toContain('watch(processFileSearch')
    expect(source).toContain('function isTaskExpanded')
    expect(source).toContain('function isDirectFileMatch')
    expect(source).toContain('function fileMatchesSearch')
    expect(source).toContain("'search-hit': directlyMatchedTaskKeys.has(taskKey(task))")
    expect(source).toContain("'file-search-hit': fileMatchesSearch(file)")
    expect(source).toContain('v-if="isTaskExpanded(task)"')
    expect(source).toContain('.task-row-button.search-hit')
    expect(source).toContain('.file-row.file-search-hit')
  })

  it('visualizes the currently filtered table tasks from an explicit action', () => {
    expect(source).not.toContain('type ProcessTab')
    expect(source).not.toContain('process-tabs')
    expect(source).not.toContain('activeTab')
    expect(source).toContain('const showGraph = ref(false)')
    expect(source).toContain('const visualizedTasks = ref<CompactionProcessTask[]>([])')
    expect(source).toContain('function visualizeTableTasks')
    expect(source).toContain('visualizedTasks.value = tableTasks.value')
    expect(source).toContain('const graphLayoutTasks = computed(() => visualizedTasks.value)')
    expect(source).toContain("window.open('', '_blank')")
    expect(source).toContain('graphWindow.opener = null')
    expect(source).not.toContain("window.open('', '_blank', 'noopener')")
    expect(source).toContain('function graphWindowHtml')
    expect(source).toContain('graphWindow.document.write(graphWindowHtml())')
    expect(source).toContain('@click="visualizeTableTasks"')
    expect(source).toContain('Visualize')
    expect(source).toContain('Compaction graph')
    expect(source).toContain('<svg')
    expect(source).not.toContain('<section v-if="showGraph" class="graph-wrap">')
  })

  it('renders file nodes as size-scaled circles', () => {
    expect(source).toContain('function fileNodeRadius')
    expect(source).toContain('r="${fileNodeRadius(node.file.sizeBytes)}"')
    expect(source).toContain('function graphFileNodeClass')
    expect(source).toContain("role: GraphFileNode['role']")
  })

  it('links an output file to a later task when it becomes an input', () => {
    expect(source).toContain('const lineageLinks = computed')
    expect(source).toContain('latestOutputByFileId')
    expect(source).toContain('function lineagePath')
    expect(source).toContain('layout.graphLinks.map')
    expect(source).toContain('class="graph-link ${link.kind === \'input\' ? \'input-link\' : \'output-link\'}"')
  })

  it('lays all tasks into one correlated left-to-right flow', () => {
    expect(source).toContain('const graphLayout = computed')
    expect(source).toContain('fileNodeById')
    expect(source).toContain('taskNodes')
    expect(source).toContain('graphLinks')
    expect(source).toContain('function graphLinkPath')
    expect(source).toContain('function graphWindowHtml')
    expect(source).toContain('<svg id="graph-svg" viewBox="0 0 ${layout.width} ${layout.height}"')
  })

  it('uses stable lanes and sorted links to reduce graph crossings', () => {
    expect(source).toContain('const laneByFileId = new Map<string, number>()')
    expect(source).toContain('const layoutTasks = [...graphLayoutTasks.value].sort((a, b) => a.timestamp - b.timestamp)')
    expect(source).toContain('layoutTasks.forEach((task, taskIndex) =>')
    expect(source).toContain('function laneForFile')
    expect(source).toContain('function assignTaskLane')
    expect(source).toContain('const inputLanes = task.inputFiles.map(file => laneForFile(file.fileId))')
    expect(source).toContain('const taskLane = assignTaskLane(inputLanes)')
    expect(source).toContain('rowByTaskId.set(taskKey(task), taskLane)')
    expect(source).toContain('function sortedByLane')
    expect(source).toContain("task.inputFiles.forEach((file) =>")
    expect(source).toContain("task.outputFiles.forEach((file) =>")
    expect(source).not.toContain('const inputRows = task.inputFiles.map(file => rowForFile(file.fileId))')
    expect(source).not.toContain('const taskRow = inputRows.length > 0 ? inputRows.reduce')
  })

  it('clips graph links to node boundaries instead of node centers', () => {
    expect(source).toContain('fromRadius:')
    expect(source).toContain('toRadius:')
    expect(source).toContain('function clipLinkEndpoint')
    expect(source).toContain('const start = clipLinkEndpoint')
    expect(source).toContain('const end = clipLinkEndpoint')
  })

  it('aims graph arrows along the center-to-center line', () => {
    expect(source).toContain('return `M ${start.x} ${start.y} L ${end.x} ${end.y}`')
  })

  it('opens the graph in a standalone browser tab', () => {
    expect(source).toContain('const graphScale = ref(1)')
    expect(source).toContain('const graphPan = ref({ x: 0, y: 0 })')
    expect(source).toContain("window.open('', '_blank')")
    expect(source).toContain('graphWindow.opener = null')
    expect(source).toContain('graphWindow.document.write(graphWindowHtml())')
    expect(source).toContain('graphWindow.document.close()')
    expect(source).toContain('showGraph.value = false')
  })

  it('escapes graph labels before writing the standalone HTML', () => {
    expect(source).toContain('function escapeHtml')
    expect(source).toContain("replace(/&/g, '&amp;')")
    expect(source).toContain("replace(/</g, '&lt;')")
    expect(source).toContain("replace(/>/g, '&gt;')")
    expect(source).toContain('escapeHtml(graphFileLabel(node.file))')
    expect(source).toContain('escapeHtml(graphFileShortLabel(node.file))')
  })

  it('simplifies graph node labels while keeping hover context', () => {
    expect(source).toContain('function graphFileShortLabel')
    expect(source).toContain('return `${file.fileId} · L${file.level} · ${formatBytes(file.sizeBytes)}`')
    expect(source).toContain("return `${file.fileId.slice(0, 8)}...${file.fileId.slice(-4)}`")
    expect(source).toContain('${escapeHtml(graphFileShortLabel(node.file))}')
    expect(source).not.toContain('{{ graphFileLabel(node.file) }}</text>')
    expect(source).toContain('${escapeHtml(formatMaybeDuration(node.task.mergeMillis))}')
    expect(source).toContain('textLength="38"')
    expect(source).toContain('font-size: 9px;')
  })

  it('keeps graph context in standalone SVG titles', () => {
    expect(source).toContain('type SelectedGraphNode')
    expect(source).toContain('const selectedGraphNode = ref<SelectedGraphNode | null>(null)')
    expect(source).toContain('const pendingGraphSelection = ref<SelectedGraphNode | null>(null)')
    expect(source).toContain('const graphDidDrag = ref(false)')
    expect(source).toContain('const graphDragThreshold = 4')
    expect(source).toContain('const graphSvgRef = ref<SVGSVGElement | null>(null)')
    expect(source).toContain('const graphCanvasRef = ref<HTMLElement | null>(null)')
    expect(source).toContain('graphViewportRevision.value\n      if (!selectedGraphNode.value) return {}')
    expect(source).toContain('function graphCssPoint')
    expect(source).toContain('const graphRenderedScale')
    expect(source).toContain('x: canvas.scrollLeft + svgRect.left - canvasRect.left')
    expect(source).toContain('y: canvas.scrollTop + svgRect.top - canvasRect.top')
    expect(source).toContain('function selectGraphFile')
    expect(source).toContain('function selectGraphTask')
    expect(source).toContain('function prepareGraphFileSelection')
    expect(source).toContain('function prepareGraphTaskSelection')
    expect(source).toContain('if (!graphDidDrag.value && pendingGraphSelection.value)')
    expect(source).toContain('function handleGraphPointerCancel')
    expect(source).toContain('pendingGraphSelection.value = null')
    expect(source).not.toContain('@click="clearGraphSelection"')
    expect(source).not.toContain('@pointerdown.stop')
    expect(source).toContain('<title>${escapeHtml(graphFileLabel(node.file))}</title>')
    expect(source).toContain('<title>${node.task.inputFileCount} input files compacted into ${node.task.outputFileCount} output files</title>')
  })

  it('writes a scrollable standalone graph canvas', () => {
    expect(source).toContain('const showGraphMinimap = computed(() => graphScale.value > 1.05)')
    expect(source).toContain('const graphViewportRevision = ref(0)')
    expect(source).toContain('function refreshGraphViewport')
    expect(source).toContain('graphViewportRevision.value')
    expect(source).toContain('class="graph-canvas"')
    expect(source).toContain('.graph-canvas{position:relative;overflow:hidden;')
    expect(source).toContain('width:${layout.width}px;height:${layout.height}px')
  })

  it('supports zoom, drag pan, and minimap in the standalone graph tab', () => {
    expect(source).toContain('id="graph-content"')
    expect(source).toContain('id="graph-minimap"')
    expect(source).toContain('id="graph-minimap-viewport"')
    expect(source).toContain('let graphScale = 1')
    expect(source).toContain('const graphPan = { x: 0, y: 0 }')
    expect(source).toContain("canvas.addEventListener('wheel', (event) =>")
    expect(source).toContain('if (!event.ctrlKey) return')
    expect(source).toContain('event.preventDefault()')
    expect(source).toContain('const nextScale = Math.min(3, Math.max(0.5, graphScale + (event.deltaY < 0 ? 0.1 : -0.1)))')
    expect(source).toContain("canvas.addEventListener('pointerdown', (event) =>")
    expect(source).toContain("canvas.addEventListener('pointermove', (event) =>")
    expect(source).toContain("canvas.addEventListener('pointerup', endDrag)")
    expect(source).toContain("content.setAttribute('transform', 'translate(' + graphPan.x + ' ' + graphPan.y + ') scale(' + graphScale + ')')")
    expect(source).toContain('minimap.style.display = \'block\'')
    expect(source).toContain('viewport.setAttribute(\'x\', String(-graphPan.x / graphScale))')
  })

  it('tracks the standalone minimap viewport in graph coordinate space', () => {
    expect(source).toContain('viewport.setAttribute(\'x\', String(-graphPan.x / graphScale))')
    expect(source).toContain('viewport.setAttribute(\'y\', String(-graphPan.y / graphScale))')
    expect(source).toContain('viewport.setAttribute(\'width\', String(canvas.clientWidth / graphScale))')
    expect(source).toContain('viewport.setAttribute(\'height\', String(canvas.clientHeight / graphScale))')
    expect(source).not.toContain('const minimapScaleX = 180 / ${layout.width}')
    expect(source).not.toContain('const minimapScaleY = 118 / ${layout.height}')
  })

  it('keeps the standalone minimap visible with a viewport rectangle', () => {
    expect(source).toContain('id="graph-minimap-viewport"')
    expect(source).toContain('minimap.style.display = \'block\'')
    expect(source).not.toContain("minimap.style.display = graphScale > 1.05 ? 'block' : 'none'")
  })

  it('uses light blue styling for the standalone minimap viewport rectangle', () => {
    expect(source).toContain('.graph-minimap-viewport{fill:rgba(125,211,252,.18);stroke:#7dd3fc;stroke-width:8}')
    expect(source).not.toContain('.graph-minimap-viewport{fill:rgba(255,255,255,.08);stroke:rgba(255,255,255,.86);stroke-width:8}')
  })

  it('positions the standalone minimap as a bottom-right overlay', () => {
    expect(source).toContain('.graph-minimap{display:block;position:absolute;right:18px;bottom:18px;min-width:0;')
    expect(source).toContain('svg{display:block;min-width:100%;width:${layout.width}px;height:${layout.height}px}')
  })

  it('sizes the standalone minimap adaptively with a quarter-window cap', () => {
    expect(source).toContain('function updateMinimapSize()')
    expect(source).toContain('const maxMinimapWidth = window.innerWidth * 0.25')
    expect(source).toContain('const maxMinimapHeight = window.innerHeight * 0.25')
    expect(source).toContain('const graphAspectRatio = ${layout.width} / ${layout.height}')
    expect(source).toContain('minimap.style.width = minimapWidth + \'px\'')
    expect(source).toContain('minimap.style.height = minimapHeight + \'px\'')
    expect(source).toContain('updateMinimapSize()')
    expect(source).not.toContain('width:180px;height:118px;')
  })

  it('provides visible zoom controls in the standalone graph tab', () => {
    expect(source).toContain('class="graph-toolbar"')
    expect(source).toContain('id="graph-zoom-out"')
    expect(source).toContain('id="graph-zoom-reset"')
    expect(source).toContain('id="graph-zoom-in"')
    expect(source).toContain('const zoomOutButton = document.getElementById(\'graph-zoom-out\')')
    expect(source).toContain('const zoomResetButton = document.getElementById(\'graph-zoom-reset\')')
    expect(source).toContain('const zoomInButton = document.getElementById(\'graph-zoom-in\')')
    expect(source).toContain('function setGraphScale(nextScale)')
    expect(source).toContain("zoomOutButton.addEventListener('click', () => setGraphScale(graphScale - 0.1))")
    expect(source).toContain("zoomResetButton.addEventListener('click', () => setGraphScale(1))")
    expect(source).toContain("zoomInButton.addEventListener('click', () => setGraphScale(graphScale + 0.1))")
  })

  it('shows standalone graph node details when users click nodes', () => {
    expect(source).toContain('id="graph-detail-panel"')
    expect(source).toContain('id="graph-detail-title"')
    expect(source).toContain('id="graph-detail-body"')
    expect(source).toContain('data-node-kind="file"')
    expect(source).toContain('data-node-kind="task"')
    expect(source).toContain('data-node-title=')
    expect(source).toContain('data-node-details=')
    expect(source).toContain('const detailPanel = document.getElementById(\'graph-detail-panel\')')
    expect(source).toContain('function showNodeDetails(node)')
    expect(source).toContain('detailPanel.style.display = \'block\'')
    expect(source).toContain('node.dataset.nodeDetails.split(\'|\')')
    expect(source).toContain("content.addEventListener('click', (event) =>")
    expect(source).toContain("content.addEventListener('keydown', (event) =>")
    expect(source).toContain('const node = event.target.closest(\'[data-node-kind]\')')
  })

  it('does not capture pointer events when users click standalone graph nodes', () => {
    expect(source).toContain("if (event.target.closest && event.target.closest('[data-node-kind]')) return")
    expect(source).toContain("if (event.target.closest && event.target.closest('.graph-toolbar')) return")
    expect(source.indexOf("event.target.closest('[data-node-kind]')")).toBeLessThan(source.indexOf('canvas.setPointerCapture(event.pointerId)'))
  })

  it('limits the graph panel height to the viewport and scrolls the graph canvas', () => {
    expect(source).toContain('max-height: calc(100vh - 120px);')
    expect(source).toContain('display: flex;')
    expect(source).toContain('flex-direction: column;')
    expect(source).toContain('flex: 1;')
    expect(source).toContain('min-height: 0;')
  })

  it('uses compact spacing for graph rows and columns', () => {
    expect(source).toContain('const rowGap = 56')
    expect(source).toContain('const fileColumnGap = 230')
    expect(source).toContain('const taskColumnGap = 230')
    expect(source).toContain('Math.max(900, ...fileNodes.map')
  })

  it('supports tracing ancestors and descendants for the selected graph node', () => {
    expect(source).toContain('const tracedGraphNode = ref<SelectedGraphNode | null>(null)')
    expect(source).toContain('const traceGraphTasks = computed(() =>')
    expect(source).toContain('const ancestorFileIds = new Set(seedFileIds)')
    expect(source).toContain('const descendantFileIds = new Set(seedFileIds)')
    expect(source).toContain('const tracedFileIds = new Set(seedFileIds)')
    expect(source).toContain('function traceGraphNode')
    expect(source).toContain('function clearGraphTrace')
    expect(source).toContain('function addAncestorTasks')
    expect(source).toContain('function addDescendantTasks')
    expect(source).toContain('task.inputFiles.some(file => fileIds.has(file.fileId))')
    expect(source).toContain('task.outputFiles.some(file => fileIds.has(file.fileId))')
    expect(source).not.toContain('task.inputFiles.forEach(file => fileIds.add(file.fileId))')
    expect(source).toContain('const graphLayoutTasks = computed(() => visualizedTasks.value)')
    expect(source).toContain('layoutTasks.forEach')
    expect(source).toContain('tracedGraphNode.value = null')
  })

  it('renders file time ranges as aligned start and end rows', () => {
    expect(source).toContain('function fileTimeStart')
    expect(source).toContain('function fileTimeEnd')
    expect(source).toContain('class="file-time-range mono"')
    expect(source).toContain('<span class="time-range-label">Start</span>')
    expect(source).toContain('<span class="time-range-label">End</span>')
    expect(source).toContain('{{ fileTimeStart(file) }}')
    expect(source).toContain('{{ fileTimeEnd(file) }}')
    expect(source).toContain('.file-time-range {')
    expect(source).toContain('.time-range-line {')
    expect(source).toContain('.time-range-label {')
    expect(source).not.toContain('<span class="mono">{{ fileTimeRange(file) }}</span>')
  })

  it('styles standalone graph nodes and labels for readability', () => {
    expect(source).toContain('const isGraphDragging = computed(() => graphDrag.value !== null)')
    expect(source).toContain('.graph-file-node {')
    expect(source).toContain('.graph-task-node {')
    expect(source).toContain('background:#0f172a')
    expect(source).toContain('border:1px solid rgba(74,144,226,.28)')
    expect(source).toContain('.graph-file-label {')
    expect(source).toContain('font-size: 10px;')
  })
})
